x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    logging: *default-logging
    volumes:
      - "./:/app"
      - ./startup.sh:/usr/local/bin/startup.sh:ro
    ports:
      - "${APP_PORT:-4200}:4200"
      - "3000:3000"
    networks:
      - setup
      
networks:
  setup:
    driver: bridge
